version: '3.8'

services:
  dot:
    build: ./dot
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  ui:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - dot
    restart: unless-stopped
